apiVersion: v1
kind: Service
metadata:
  name: psi5120-service
spec:
  selector:
    app: psi5120
  ports:
  - name: psi5120
    protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 30071
  externalIPs:
  - 40.76.39.130
  type: NodePort
