apiVersion: apps/v1
kind: Deployment
metadata:
 name: psi5120-deploy
spec:
 replicas: 20
 selector:
  matchLabels:
   app: psi5120
 template:
  metadata:
   labels:
    app: psi5120
  spec:
   containers:
   - name: psi5120-container
     image: pmigliatti/psi5120
     resources:
       requests:
         memory: "10Gi"
       limits:
         memory: "15Gi"
# --vm 2 ... start two virtual worker threads
# --vm-bytes ... allocate 8GB of RAM
# --vm-hang ... randomly waits 2 seconds and re-allocate around 8 GB of ram
     args: ["--vm", "20", "--vm-bytes", "12G", "--vm-hang", "5"]
     imagePullPolicy: Always
     ports:
     - containerPort: 5050
   restartPolicy: Always
